### PR TITLE
Add CMake

### PR DESCRIPTION
**Pull request by otreblan**
The Makefile was removed

### CODE REVIEW

**Comment by otreblan** [comment]
Also added to the [aur](https://aur.archlinux.org/packages/paleofetch-git/), but until this is merged it will use my fork because CMake.

**Comment by ss7m** [comment]
I'm not an experienced C programmer- what advantage does cmake have over regular make, especially for a project as small as this?

**Comment by otreblan** [comment]
CMake is a build system generator. It can be used for more than making Makefiles.
https://stackoverflow.com/questions/25789644/difference-between-using-makefile-and-cmake-to-compile-the-code

**Comment by ss7m** [comment]
Would you mind also updating the README to reflect the changed installation process?

**Comment by otreblan** [comment]
ok

**Comment by ss7m** [comment]
I appreciate your taking interest in my project, but I'm still not convinced there's much to gain from using CMake, versus what I perceive to be the added complexity. Considering that the source code consists of 1 file, and that this change will make it harder for me to maintain this in the future, I don't think I'm going to merge this at this time.

**Comment by Titaniumtown** [comment]
can this pull request be re-opened?

**Pull request closed without merging**
