### PR TITLE
Resort to fallback method if we can't get the active window (Fixes #38)

### LINKED ISSUE #38: Error of failed request: BadWindow
Hi,
I get the following error when running `paleofetch`. I am currently on the latest commit.

Screenshot from 2020-04-24 10-06-54

[Edit]
The issue occurs in the `get_terminal` call. Commenting out that line resolves the issue. I am using `gnome-terminal` if that helps.

### PR DESCRIPTION
**Pull request by allisio**

### CODE REVIEW

**Comment by ss7m** [comment]
I'm not sure I'm so comfortable putting a `goto` into the code

**Comment by allisio** [comment]
Why's that?

**Comment by ss7m** [comment]
Upon further thought, I suppose it's fine. I think I just have a negative response to `goto` statements ingrained in me, perhaps unfairly.

**Comment by allisio** [comment]
They can certainly be used to write extremely confusing and hard-to-follow code, but we're just doing a very short hop here to avoid a bit of code duplication.

**Pull request merged**
